WebAppMango/Controllers/AuthAPIController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using WebAppMango.Models.DTO;
using WebAppMango.Services;
using WebAppMango.Utilities;

namespace WebAppMango.Controllers
{
    public class AuthAPIController : Controller
    {
        private readonly IAuthService _authService;
        private readonly ITokenProvider _tokenProvider;
        public AuthAPIController(IAuthService authService, ITokenProvider tokenProvider)
        {
            _authService = authService;
            _tokenProvider = tokenProvider;
        }

        [HttpGet]
        public IActionResult Login()
        {
            LoginRequestDTO loginRequestDTO = new LoginRequestDTO();
            return View(loginRequestDTO);
        }


        [HttpGet]
        public IActionResult Register()
        {
            var roleList = new List<SelectListItem>()
            {
                new SelectListItem() { Text=SD.RoleAdmin,Value= SD.RoleAdmin},
                new SelectListItem() { Text=SD.RoleCustomer,Value= SD.RoleCustomer},
            };
            ViewBag.RoleList = roleList;
            return View();
        }




        [HttpGet]
        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            _tokenProvider.ClearToken();
            return RedirectToAction("Index", "Home");
        }

        [HttpPost]
        public async Task<IActionResult> Login(LoginRequestDTO loginRequestDTO)
        {
            if(ModelState.IsValid )
            {
                ResponseDTO? responseDTO = await _authService.Login(loginRequestDTO);
                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    LoginResponseDTO loginResponseDTO = JsonConvert.DeserializeObject<LoginResponseDTO>(Convert.ToString(responseDTO.Result));
                    await SignInUser(loginResponseDTO);
                    _tokenProvider.SetToken(loginResponseDTO.Token);
                    return RedirectToAction("Index", "Home");
                }
            }
           
            return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> Register(RegisterRequestDTO registerRequestDTO)
        {
                ResponseDTO? responseDTO = await _authService.Registration(registerRequestDTO);
                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    if (string.IsNullOrEmpty(registerRequestDTO.Role))
                    {
                        registerRequestDTO.Role = SD.RoleCustomer;

                    }
                    ResponseDTO? assignRole = await _authService.AssignRole(registerRequestDTO);
                    if (assignRole != null && assignRole.IsSuccess)
                    {
                        TempData["Success"] = "Registration Successfull";
                        return RedirectToAction(nameof(Login));
                    }
                }
                else
                {
                TempData["error"] = responseDTO?.Message;
                var roleList = new List<SelectListItem>()
                    {
                     new SelectListItem() { Text=SD.RoleAdmin,Value= SD.RoleAdmin},
                     new SelectListItem() { Text=SD.RoleCustomer,Value= SD.RoleCustomer},
                    };
                    ViewBag.RoleList = roleList;
                    return View(roleList);
                }
            return View(registerRequestDTO);
        }

        private  async Task SignInUser(LoginResponseDTO dto)
        {
            var handler = new JwtSecurityTokenHandler();
            try
            {
                var jwt = handler.ReadJwtToken(dto.Token);
                var identity = new ClaimsIdentity(CookieAuthenticationDefaults.AuthenticationScheme);
                identity.AddClaim(new Claim(JwtRegisteredClaimNames.Email, jwt.Claims.FirstOrDefault(u => u.Type == JwtRegisteredClaimNames.Email).Value));
                identity.AddClaim(new Claim(JwtRegisteredClaimNames.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Name).Value));
                identity.AddClaim(new Claim(JwtRegisteredClaimNames.Sub, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Sub).Value));
                identity.AddClaim(new Claim(ClaimTypes.Role, jwt.Claims.FirstOrDefault(x => x.Type == "role").Value));
                identity.AddClaim(new Claim(ClaimTypes.Name, jwt.Claims.FirstOrDefault(x => x.Type == JwtRegisteredClaimNames.Email).Value));

                var principle = new ClaimsPrincipal(identity);
                await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, principle);
            }
            catch(Exception e)
            {
                throw new Exception(e.Message);
            }   

           
        }
    }
 }

WebAppMango/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.JsonWebTokens;
using Newtonsoft.Json;
using WebAppMango.Models.DTO;
using WebAppMango.Services;
using WebAppMango.Utilities;

namespace WebAppMango.Controllers
{
    public class CartController : Controller
    {
        private readonly ICartService _cartService;
        private readonly IOrderService _orderService;
        public CartController(ICartService cartService, IOrderService orderService)
        {
            _cartService = cartService;
            _orderService = orderService;
        }

        [HttpGet]
        public async Task<IActionResult> CartIndex()
         {
            try
            {
                var userId = User.Claims.Where(x=>x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
                ResponseDTO? responseDTO = await _cartService.GetCart(userId);
                CartDTO cartDTO = null;
                    
                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    cartDTO = JsonConvert.DeserializeObject<CartDTO>(Convert.ToString(responseDTO.Result));
                }
                return View(cartDTO);
            }
             catch (Exception ex) 
            {
                TempData["error"] = ex.Message;
            }
             return View();
        }

        [HttpGet]
        public async Task<IActionResult> CheckOut()
        {
            return View(await LoggedInUser());
        }


        [HttpGet]
        public async Task<IActionResult> Confirmation(int orderId)
        {
            try
            {
                ResponseDTO? responseDTO = await _orderService.ValidateStripeSession(orderId);
                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    OrderHeaderDTO orderHeaderDTO = JsonConvert.DeserializeObject<OrderHeaderDTO>(Convert.ToString(responseDTO.Result));
                    if(orderHeaderDTO.StatusCode == SD.Status_Approved)
                    {
                        return View(orderId);
                    }                   
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return View();     
        }


        [HttpPost]
        [ActionName("CheckOut")]
        public async Task<IActionResult> CheckOut(CartDTO cartDTO)
        {
            try
            {
                CartDTO cart = await LoggedInUser();
                cart.CartHeaderDTO.PhoneNumber = cartDTO.CartHeaderDTO.PhoneNumber;
                cart.CartHeaderDTO.Name = cartDTO.CartHeaderDTO.Name;
                cart.CartHeaderDTO.EmailId = cartDTO.CartHeaderDTO.EmailId;

                ResponseDTO? responseDTO = await _orderService.CreateOrder(cart);
                OrderHeaderDTO orderHeaderDTO = JsonConvert.DeserializeObject<OrderHeaderDTO>(Convert.ToString(responseDTO.Result));
                if (responseDTO.IsSuccess && responseDTO != null)
                {
                    var domain = Request.Scheme + "://" + Request.Host.Value + "/";
                    StripeRequestDTO stripeRequestDTO = new StripeRequestDTO()
                    {
                        ApprovelURL = domain + "cart/Confirmation?orderId=" + orderHeaderDTO.OrderHeaderId,
                        CancelURL = domain + "cart/CheckOut",
                        OrderHeaderDTO = orderHeaderDTO
                    };
                    var response = await _orderService.CreateSession(stripeRequestDTO);
                    StripeRequestDTO stripeRequest = JsonConvert.DeserializeObject<StripeRequestDTO>(Convert.ToString(response.Result));
                    Response.Headers.Add("Location",stripeRequest.StripeSessionUrl);
                    return new StatusCodeResult(303);
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return View();

        }


        [HttpPost]
        public async Task<IActionResult> EmailCart(CartDTO cartDTO)
        {
                CartDTO cart = await LoggedInUser();
                cart.CartHeaderDTO.EmailId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Email)?.FirstOrDefault()?.Value;
                ResponseDTO? responseDTO = await _cartService.EmailCart(cart);

                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    TempData["success"] = "Email will be processed and sent shortly.";
                    return RedirectToAction(nameof(CartIndex));
                }
              
                return View(cartDTO);
            }

        private async Task<CartDTO> LoggedInUser()
        {
            var userId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
            ResponseDTO? responseDTO = await _cartService.GetCart(userId);

            if (responseDTO != null && responseDTO.IsSuccess)
            {
                CartDTO cartDTO = JsonConvert.DeserializeObject<CartDTO>(Convert.ToString(responseDTO.Result));
                return cartDTO;
            }
            return new CartDTO();
        }

        public async Task<IActionResult> Remove(int cartDetailsId)
        {
            try
            {
               var userId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
                ResponseDTO? responseDTO = await _cartService.RemoveCart(cartDetailsId);

                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    TempData["success"] = "Item has been removed from cart";
                    return RedirectToAction(nameof(CartIndex));
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> ApplyCoupon(CartDTO cartDTO)
        {
            try
            {
                var userId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
                ResponseDTO? responseDTO = await _cartService.ApplyCoupon(cartDTO);

                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    TempData["success"] = "Coupon has been added to the Total Amount";
                    return RedirectToAction(nameof(CartIndex));
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return View();
        }



        [HttpPost]

        public async Task<IActionResult> RemoveCoupon(CartDTO cartDTO)
        {
            try
            {
                cartDTO.CartHeaderDTO.CouponCode = "";
                var userId = User.Claims.Where(x => x.Type == JwtRegisteredClaimNames.Sub)?.FirstOrDefault()?.Value;
                ResponseDTO? responseDTO = await _cartService.RemoveCoupon(cartDTO);

                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    TempData["success"] = "Coupon has been removed from the Total Amount";
                    return RedirectToAction(nameof(CartIndex));
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
            }
            return View();
        }
    }
}

WebAppMango/Controllers/CouponController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WebAppMango.Models.DTO;
using WebAppMango.Services;

namespace WebAppMango.Controllers
{
    public class CouponController : Controller
    {
        private readonly ICouponService _couponService;
        public CouponController(ICouponService couponService)
        {
            _couponService = couponService;
        }
        public async Task<IActionResult> CouponIndex()
        {
            List<CouponDTO> couponlist = new List<CouponDTO>();
            ResponseDTO? responseDTO  = await _couponService.GetAllCouponAsync();
            if(responseDTO!=null && responseDTO.IsSuccess)
            {
                couponlist = JsonConvert.DeserializeObject<List<CouponDTO>>(Convert.ToString(responseDTO.Result));
            }

            return View(couponlist);
        }

        public async Task<IActionResult> CreateCoupon()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateCoupon(CouponDTO couponDTO)
        {
            if(ModelState.IsValid)
            {
                ResponseDTO? responseDTO = await _couponService.AddAsync(couponDTO);
                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    TempData["success"] = "Successfully Created Coupon";
                    return RedirectToAction(nameof(CouponIndex));
                }
            }
            else
            {
                TempData["error"] = "Failed to create Coupon";
            }
            return View(couponDTO);
        }
        public async Task<IActionResult> CouponDelete(int couponId)
        {
            CouponDTO coupondto = new();
            ResponseDTO? responseDTO = await _couponService.GetByIdAsync(couponId);
            if (responseDTO != null && responseDTO.IsSuccess)
            {
				coupondto = JsonConvert.DeserializeObject<CouponDTO>(Convert.ToString(responseDTO.Result));
                return View(coupondto);
            }
            else
            {
                TempData["error"] = responseDTO?.Message;
            }

            return NotFound();
        }


        [HttpPost]
        public async Task<IActionResult> CouponDelete(CouponDTO coupon)
        {
            if (ModelState.IsValid)
            {
                ResponseDTO? responseDTO = await _couponService.RemoveAsync(coupon.CouponId);
                if (responseDTO != null && responseDTO.IsSuccess)
                {
                    TempData["success"] = "Successfully Deleted Coupon";
                    return RedirectToAction(nameof(CouponIndex));
                }
            }
            else
            {
                TempData["error"] = "Failed to delete Coupon";
            }
            return NotFound();
        }
    }
}

WebAppMango/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebAppMango</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebAppMango.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebAppMango</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Content Management
                            </a>
                            <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink">
                                <li><a class="dropdown-item" asp-controller="Coupon" asp-action="CouponIndex">Coupon</a></li>
                                <li><a class="dropdown-item" asp-controller="Product" asp-action="ProductIndex">Product</a></li>
                            </ul>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-controller="Cart" asp-action="CartIndex">
                                &nbsp;<i class="bi bi-cart"></i>&nbsp;
                            </a>
                        </li>

                    </ul>
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <ul class="nav navbar-nav float-md-right">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AuthAPI" asp-action="Register">Register</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="AuthAPI" asp-action="Login">Login</a>
                            </li>
                          
                        </ul>
                    }
                    else
                    {
                    <ul class="nav navbar-nav float-md-right">
                            <li class="nav-item">
                                <a class="nav-link" href="#" >Hello, @User.Identity.Name</a>
                            </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AuthAPI" asp-action="Logout">Logout</a>
                        </li>
                          
                    </ul>
                    }
                </div>
               
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
            <partial name="_NotificationScriptPartial"/>
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container text-center">
            &copy; 2024 - WebAppMango -Made with <i class="bi bi-balloon-heart"> by Rupa Chowdhury</i>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

WebAppMango/Views/Shared/_NotificationScriptPartial.cshtml
@if(TempData["error"]!=null)
{
	<!-- jQuery -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Toastr -->
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.error('@TempData["error"]')
    </script>
}
@if (TempData["success"] != null)
{
	<!-- jQuery -->
	<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
	<!-- Toastr -->
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script type="text/javascript">
        toastr.success('@TempData["success"]')
    </script>
}